Final template/taskcat changes

diff --git a/templates/ammos-cubs-editor.template.yaml b/templates/ammos-cubs-editor.template.yaml
--- a/templates/ammos-cubs-editor.template.yaml
+++ b/templates/ammos-cubs-editor.template.yaml
@@ -7,6 +7,7 @@ Parameters:
   ConfigBucketName:
     Description: Name of the S3 bucket used to store project-specific configuration files.
     Type: String
+    Default: ''
   FQDN:
     Description: Fully Qualified Domain Name to use for project resources root.
     Type: String
@@ -72,6 +73,7 @@ Conditions:
   IsGovCloud: !Not [!Equals ['aws', !Ref AWS::Partition]]
   RolePathProvided: !Not [!Equals ['', !Ref RolePath]]
   PermissionsBoundaryProvided: !Not [!Equals ['', !Ref PermissionsBoundaryArn]]
+  UserProvidedConfigBucket: !Not [!Equals ['', !Ref ConfigBucketName]]
 Resources:
   AitEditorSecurityGroup:
     Type: AWS::EC2::SecurityGroup
@@ -160,98 +162,104 @@ Resources:
       SubnetId: !Select [0, !Ref PrivateSubnetIds]
       UserData:
         Fn::Base64:
-          !Sub |
-          #!/bin/bash
-          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
+          !Sub
+          - |
+            #!/bin/bash
+            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
 
-          function exitTrap(){
-            exitCode=$?
-            /opt/aws/bin/cfn-signal \
-              --stack ${AWS::StackName} \
-              --resource Instance \
-              --region ${AWS::Region} -e $exitCode || echo 'Failed to send Cloudformation Signal'
-          }
-          trap exitTrap EXIT
-          CONFIG_BUCKET_NAME=${ConfigBucketName}
+            function exitTrap(){
+              exitCode=$?
+              /opt/aws/bin/cfn-signal \
+                --stack ${AWS::StackName} \
+                --resource Instance \
+                --region ${AWS::Region} -e $exitCode || echo 'Failed to send Cloudformation Signal'
+            }
+            trap exitTrap EXIT
+            CONFIG_BUCKET_NAME=${ConfigBucket}
 
-          yum install -y -q python3 wget unzip
-          mkdir -p /opt/aws/bin
-          wget -nv https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
-          pip3 install aws-cfn-bootstrap-py3-latest.tar.gz
-          ln -s /usr/local/bin/cfn-* /opt/aws/bin
-          wget -nv https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
-          rpm -U ./amazon-cloudwatch-agent.rpm
-          yum install -y -q https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
+            yum install -y -q python3 wget unzip
+            mkdir -p /opt/aws/bin
+            wget -nv https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
+            pip3 install aws-cfn-bootstrap-py3-latest.tar.gz
+            ln -s /usr/local/bin/cfn-* /opt/aws/bin
+            wget -nv https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
+            rpm -U ./amazon-cloudwatch-agent.rpm
+            yum install -y -q https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
 
-          # Set variables for system install
-          USER=ec2-user
-          PROJECT_HOME=/home/$USER
-          SETUP_DIR=$PROJECT_HOME/setup
-          AWS_REGION=${AWS::Region}
-          AWS_ACCOUNT_ID=${AWS::AccountId}
-          EDITOR_IMAGE_URI=codercom/code-server
-          EDITOR_IMAGE_TAG=3.11.0
+            # Set variables for system install
+            USER=ec2-user
+            PROJECT_HOME=/home/$USER
+            SETUP_DIR=$PROJECT_HOME/setup
+            AWS_REGION=${AWS::Region}
+            AWS_ACCOUNT_ID=${AWS::AccountId}
+            EDITOR_IMAGE_URI=codercom/code-server
+            EDITOR_IMAGE_TAG=3.11.0
 
-          echo "Starting user data"
+            echo "Starting user data"
 
-          # General tools
-          yum install -y -q yum-utils git vim
-          curl -SL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -o /usr/bin/jq
-          chmod +x /usr/bin/jq
+            # General tools
+            yum install -y -q yum-utils git vim
+            curl -SL https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -o /usr/bin/jq
+            chmod +x /usr/bin/jq
 
-          # Install AWS CLI
-          echo "Installing AWS CLI"
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip -qq awscliv2.zip
-          ./aws/install
+            # Install AWS CLI
+            echo "Installing AWS CLI"
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip -qq awscliv2.zip
+            ./aws/install
 
-          # Pull assets, config, and secrets from s3/sm
-          mkdir -p $SETUP_DIR
-          cd $SETUP_DIR
-          /usr/local/aws-cli/v2/current/bin/aws --region $AWS_REGION s3 cp \
-            s3://$CONFIG_BUCKET_NAME/configs/editor/cloudwatch-agent-editor.json \
-            $SETUP_DIR/cloudwatch-agent-editor.json
+            # Pull assets, config, and secrets from s3/sm
+            mkdir -p $SETUP_DIR
+            cd $SETUP_DIR
+            /usr/local/aws-cli/v2/current/bin/aws --region $AWS_REGION s3 cp \
+              s3://$CONFIG_BUCKET_NAME/configs/editor/cloudwatch-agent-editor.json \
+              $SETUP_DIR/cloudwatch-agent-editor.json
 
-          # Docker + Docker-Compose
-          echo "Installing Docker components"
-          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
-          yum install -y -q docker-ce docker-ce-cli containerd.io
-          groupadd docker
-          usermod -aG docker $USER
-          systemctl enable docker
-          systemctl start docker
+            # Docker + Docker-Compose
+            echo "Installing Docker components"
+            yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
+            yum install -y -q docker-ce docker-ce-cli containerd.io
+            groupadd docker
+            usermod -aG docker $USER
+            systemctl enable docker
+            systemctl start docker
 
-          echo "Creating Editor Users"
-          groupadd editor-users
-          EDITOR_GID=$(tail -1 /etc/group | cut -d : -f3)
-          PORT=80
-          USERNAME=editor-user
-          # Create user in editor-users group
-          useradd -m -g editor-users -G docker $USERNAME
-          EDITOR_UID=$(id -u $USERNAME)
+            echo "Creating Editor Users"
+            groupadd editor-users
+            EDITOR_GID=$(tail -1 /etc/group | cut -d : -f3)
+            PORT=80
+            USERNAME=editor-user
+            # Create user in editor-users group
+            useradd -m -g editor-users -G docker $USERNAME
+            EDITOR_UID=$(id -u $USERNAME)
 
-          # Aerie Editor Config
-          mkdir -p /home/$USERNAME/.aerie-editor-config/code-server
-          mkdir /home/$USERNAME/.aerie-editor-data
-          tee /home/$USERNAME/.aerie-editor-config/code-server/config.yaml << EOF
-          auth: none
-          bind-addr: 127.0.0.1:8080
-          cert: false
-          disable-telemetry: true
-          disable-update-check: true
-          extra-extensions-dir: ['/home/coder/extra-extensions']
-          # username: $USERNAME
-          EOF
-          chown -R $USERNAME: /home/$USERNAME
+            # Aerie Editor Config
+            mkdir -p /home/$USERNAME/.aerie-editor-config/code-server
+            mkdir /home/$USERNAME/.aerie-editor-data
+            tee /home/$USERNAME/.aerie-editor-config/code-server/config.yaml << EOF
+            auth: none
+            bind-addr: 127.0.0.1:8080
+            cert: false
+            disable-telemetry: true
+            disable-update-check: true
+            extra-extensions-dir: ['/home/coder/extra-extensions']
+            # username: $USERNAME
+            EOF
+            chown -R $USERNAME: /home/$USERNAME
 
-          # Aerie Editor startup
-          docker run --name aerie-editor-$USERNAME -d -p $PORT:8080 \
-            -v /home/$USERNAME/.aerie-editor-data:/home/coder/.local/share/code-server \
-            -v /home/$USERNAME/.aerie-editor-config:/home/coder/.config \
-            -v /home/$USERNAME:/home/coder/project \
-            -u $EDITOR_UID:$EDITOR_GID \
-            $EDITOR_IMAGE_URI:$EDITOR_IMAGE_TAG;
-          /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:$SETUP_DIR/cloudwatch-agent-editor.json
+            # Aerie Editor startup
+            docker run --name aerie-editor-$USERNAME -d -p $PORT:8080 \
+              -v /home/$USERNAME/.aerie-editor-data:/home/coder/.local/share/code-server \
+              -v /home/$USERNAME/.aerie-editor-config:/home/coder/.config \
+              -v /home/$USERNAME:/home/coder/project \
+              -u $EDITOR_UID:$EDITOR_GID \
+              $EDITOR_IMAGE_URI:$EDITOR_IMAGE_TAG;
+            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:$SETUP_DIR/cloudwatch-agent-editor.json
+          - ConfigBucket: !If
+            - UserProvidedConfigBucket
+            - !Ref ConfigBucketName
+            - Fn::ImportValue:
+                Fn::Sub: "${ProjectName}-ConfigBucketName"
   InstanceRole:
     Type: AWS::IAM::Role
     Properties:
@@ -282,8 +290,20 @@ Resources:
                   - s3:ListBucket
                 Effect: Allow
                 Resource:
-                  - !Sub 'arn:${AWS::Partition}:s3:::${ConfigBucketName}'
-                  - !Sub 'arn:${AWS::Partition}:s3:::${ConfigBucketName}/*'
+                  - !Sub
+                    - 'arn:${AWS::Partition}:s3:::${ConfigBucket}'
+                    - ConfigBucket: !If
+                      - UserProvidedConfigBucket
+                      - !Ref ConfigBucketName
+                      - Fn::ImportValue:
+                          Fn::Sub: "${ProjectName}-ConfigBucketName"
+                  - !Sub
+                    - 'arn:${AWS::Partition}:s3:::${ConfigBucket}/*'
+                    - ConfigBucket: !If
+                      - UserProvidedConfigBucket
+                      - !Ref ConfigBucketName
+                      - Fn::ImportValue:
+                          Fn::Sub: "${ProjectName}-ConfigBucketName"
             Version: '2012-10-17'
           PolicyName: InstanceRoleDefaultPolicy
 
