Add auth actions, fix editor userdata, add cognito-inspect

diff --git a/templates/ammos-cubs-editor.template.yaml b/templates/ammos-cubs-editor.template.yaml
--- a/templates/ammos-cubs-editor.template.yaml
+++ b/templates/ammos-cubs-editor.template.yaml
@@ -29,12 +29,19 @@ Parameters:
   SshKeyName:
     Description: Name of created SSH Key for instance access - must use SSM sessions if no key supplied
     Type: String
+  SessionTimeout:
+    Description: The maximum duration of the authentication session, in seconds.
+    Type: Number
+    Default: 604800  # One day
+    MinValue: 60
+    MaxValue: 604800
   # NOTE: This will be obsolete once AIT Editor is open sourced and publicly available
   EditorEcrRepoArn:
     Type: String
 
 Conditions:
   SshEnabled: !Not [!Equals ['', !Ref SshKeyName]]
+  IsGovCloud: !Not [!Equals ['aws', !Ref AWS::Partition]]
 
 Resources:
   AitEditorSecurityGroup:
@@ -67,11 +74,50 @@ Resources:
   EditorListenerRule:
     Type: AWS::ElasticLoadBalancingV2::ListenerRule
     Properties:
-      # TODO: Add authenticate action
       Actions:
-        - TargetGroupArn:
+        - Type: authenticate-oidc
+          Order: 1
+          AuthenticateOidcConfig:
+            ClientId: !ImportValue
+              Fn::Sub: ${ProjectName}-CognitoClientId
+            ClientSecret: !ImportValue
+              Fn::Sub: ${ProjectName}-CognitoClientSecret
+            Issuer: !ImportValue
+              Fn::Sub: ${ProjectName}-CognitoProviderUrl
+            UserInfoEndpoint:
+              Fn::Join:
+                - ""
+                - - "https://"
+                  - !ImportValue
+                    Fn::Sub: ${ProjectName}-CognitoDomainName
+                  - !If [IsGovCloud, ".auth-fips.", ".auth."]
+                  - !Ref AWS::Region
+                  - ".amazoncognito.com/oauth2/userInfo"
+            AuthorizationEndpoint:
+              Fn::Join:
+                - ""
+                - - "https://"
+                  - !ImportValue
+                    Fn::Sub: ${ProjectName}-CognitoDomainName
+                  - !If [IsGovCloud, ".auth-fips.", ".auth."]
+                  - !Ref AWS::Region
+                  - ".amazoncognito.com/oauth2/authorize"
+            TokenEndpoint:
+              Fn::Join:
+                - ""
+                - - "https://"
+                  - !ImportValue
+                    Fn::Sub: ${ProjectName}-CognitoDomainName
+                  - !If [IsGovCloud, ".auth-fips.", ".auth."]
+                  - !Ref AWS::Region
+                  - ".amazoncognito.com/oauth2/token"
+            OnUnauthenticatedRequest: authenticate
+            Scope: openid
+            SessionTimeout: !Ref SessionTimeout
+        - Type: forward
+          Order: 2
+          TargetGroupArn:
             Ref: EditorTargetGroup
-          Type: forward
       Conditions:
         - Field: host-header
           HostHeaderConfig:
@@ -113,7 +159,7 @@ Resources:
             /opt/aws/bin/cfn-signal \
               --stack ${AWS::StackName} \
               --resource Instance \
-              --region ${AWS::Region} -e $!exitCode || echo 'Failed to send Cloudformation Signal'
+              --region ${AWS::Region} -e $exitCode || echo 'Failed to send Cloudformation Signal'
           }
           trap exitTrap EXIT
           CONFIG_BUCKET_NAME=${ConfigBucketName}
@@ -124,7 +170,7 @@ Resources:
           pip3 install aws-cfn-bootstrap-py3-latest.tar.gz
           ln -s /usr/local/bin/cfn-* /opt/aws/bin
           wget -nv https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
-          sudo rpm -U ./amazon-cloudwatch-agent.rpm
+          rpm -U ./amazon-cloudwatch-agent.rpm
           yum install -y -q https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
 
           # Set variables for system install
@@ -153,8 +199,9 @@ Resources:
           # Pull assets, config, and secrets from s3/sm
           mkdir -p $SETUP_DIR
           cd $SETUP_DIR
-          /usr/local/aws-cli/v2/current/bin/aws --region $AWS_REGION s3 cp s3://$CONFIG_BUCKET_NAME/editor/cloudwatch-agent-editor.json
-          $SETUP_DIR/cloudwatch-agent-editor.json
+          /usr/local/aws-cli/v2/current/bin/aws --region $AWS_REGION s3 cp \
+            s3://$CONFIG_BUCKET_NAME/editor/cloudwatch-agent-editor.json \
+            $SETUP_DIR/cloudwatch-agent-editor.json
 
           # Docker + Docker-Compose
           echo "Installing Docker components"
@@ -166,41 +213,41 @@ Resources:
           systemctl start docker
 
           echo "Authenticating to ECR"
-          /usr/local/aws-cli/v2/current/bin/aws ecr get-login-password --region
-          $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
+          /usr/local/aws-cli/v2/current/bin/aws ecr get-login-password --region $AWS_REGION | \
+            docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
 
           # docker-compose up --detach
 
           echo "Creating Editor Users"
           groupadd editor-users
           EDITOR_GID=$(tail -1 /etc/group | cut -d : -f3)
-          PORT=8080
-          for USERNAME in editor-user-0; do
-            # Create user in editor-users group
-            useradd -m -g editor-users -G docker $USERNAME
-            EDITOR_UID=$(id -u $USERNAME)
+          PORT=80
+          USERNAME=editor-user
+          # Create user in editor-users group
+          useradd -m -g editor-users -G docker $USERNAME
+          EDITOR_UID=$(id -u $USERNAME)
 
-            # Aerie Editor Config
-            mkdir -p /home/$USERNAME/.aerie-editor-config/code-server
-            mkdir /home/$USERNAME/.aerie-editor-data
-            tee /home/$USERNAME/.aerie-editor-config/code-server/config.yaml << EOF
-              auth: none
-              bind-addr: 127.0.0.1:8080
-              cert: false
-              disable-telemetry: true
-              disable-update-check: true
-              extra-extensions-dir: [''/home/coder/extra-extensions'']
-              username: $USERNAME
+          # Aerie Editor Config
+          mkdir -p /home/$USERNAME/.aerie-editor-config/code-server
+          mkdir /home/$USERNAME/.aerie-editor-data
+          tee /home/$USERNAME/.aerie-editor-config/code-server/config.yaml << EOF
+          auth: none
+          bind-addr: 127.0.0.1:8080
+          cert: false
+          disable-telemetry: true
+          disable-update-check: true
+          extra-extensions-dir: ['/home/coder/extra-extensions']
+          username: $USERNAME
           EOF
-            chown -R $USERNAME: /home/$USERNAME
+          chown -R $USERNAME: /home/$USERNAME
 
-            # Aerie Editor startup
-            docker run --name aerie-editor-$USERNAME -d -p $PORT:8080 -v /home/$USERNAME/.aerie-editor-data:/home/coder/.local/share/code-server -v /home/$USERNAME/.aerie-editor-config:/home/coder/.config \
+          # Aerie Editor startup
+          docker run --name aerie-editor-$USERNAME -d -p $PORT:8080 \
+            -v /home/$USERNAME/.aerie-editor-data:/home/coder/.local/share/code-server \
+            -v /home/$USERNAME/.aerie-editor-config:/home/coder/.config \
             -v /home/$USERNAME:/home/coder/project \
             -u $EDITOR_UID:$EDITOR_GID \
             $EDITOR_IMAGE_URI:$EDITOR_IMAGE_TAG;
-            ((++PORT))
-          done;
           /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:$SETUP_DIR/cloudwatch-agent-editor.json
   InstanceRole:
     Type: AWS::IAM::Role
